#!/bin/bash

set -eou pipefail
shopt -s extglob nullglob

BRANCH=${1}

git clone --branch $BRANCH ${PANTHEON_GIT_URL} wordpress

# Replace the theme directory with this one.
rm -rf wordpress/wp-content/themes/${THEME_NAME}/*
mv ./!(wordpress) wordpress/wp-content/themes/${THEME_NAME}