#!/bin/bash

set -eou pipefail

COMMIT_MSG=$(git log -1 --pretty=%B)
cd wordpress

git config --global user.email "${GIT_EMAIL}"
git config --global user.name "GitHub Actions"

STATUS=$(git status --porcelain)
if [ -n "$STATUS" ]; then
    git add *
    git commit . --message="Deploy from GitHub: ${COMMIT_MSG}"

    # @todo push to the right multidev if this was to a branch
    git push origin HEAD:master
fi