name: Multidevs for PRs

on:
  pull_request:
    types: [opened]

env:
  PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Terminus
      uses: ackama/setup-terminus@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

    - name: Create Multidev
      run: |
        terminus multidev:create $PANTHEON_SITE_ID.live pr-$PR_NUMBER

    - name: Set Up SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/pantheon-ssh

    - name: Clone Pantheon WordPress and Replace the Theme
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/build-theme pr-$PR_NUMBER

    - name: Commit Theme and Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/commit-push pr-$PR_NUMBER

    - name: Cleanup
      if: always()
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-add -D
        rm -Rf *
