name: Cleanup Multidevs

on:
  pull_request:
    types: [ closed ]
env:
  PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}

jobs:
  pantheon_cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Terminus
      uses: ackama/setup-terminus@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

    - name: Delete Multidev
      run: |
        terminus multidev:delete $PANTHEON_SITE_ID.pr-${{ github.event.number }}