name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}
  PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  THEME_NAME: ${{ github.event.repository.name }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/pantheon-ssh

    - name: Clone Pantheon WordPress and Replace the Theme
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        shopt -s extglob nullglob
        git clone ${PANTHEON_GIT_URL} wordpress
        rm -rf wordpress/wp-content/themes/${THEME_NAME}/*
        mv ./!(wordpress) wordpress/wp-content/themes/${THEME_NAME}
      shell:
        bash

    - name: Commit Theme and Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/commit-push

    - name: Cleanup
      if: always()
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-add -D
        rm -Rf *