name: Deploy to Pantheon

on: [push]
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}
  PANTHEON_GIT_URL: "ssh://codeserver.dev.${PANTHEON_SITE_ID}@codeserver.dev.${PANTHEON_SITE_ID}.drush.in:2222/~/repository.git"
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  THEME_NAME: ${{ github.event.repository.name }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/pantheon-ssh

    - name: Clone Pantheon WordPress and Replace the Theme
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/build-theme master

    - name: Commit Theme and Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/commit-push master

    - name: Cleanup
      if: always()
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-add -D
        rm -Rf *