name: Deploy to Pantheon

on:
  push:
    branches:
      - 'main'
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  THEME_NAME: ${{ github.event.repository.name }}
  PANTHEON_DEFAULT_BRANCH: "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.1

    - name: Set Up SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/pantheon-ssh

    - name: Clone Pantheon WordPress and Replace the Theme
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/build-theme $PANTHEON_DEFAULT_BRANCH

    - name: Commit Theme and Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ./.ci/commit-push $PANTHEON_DEFAULT_BRANCH

    - name: Cleanup
      if: always()
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-add -D
        rm -Rf *