name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        config:
          Host *.drush.in
            StrictHostKeyChecking no
        known_hosts:
          ssh-keyscan -p 2222 codeserver.dev.d59882c1-ed01-4646-a63e-16b6f9cfa5d3.drush.in
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_GIT_URL }}'
      run: |
        git remote add pantheon $pantheon_repo
        git push pantheon HEAD:master