name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: deployer
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PANTHEON_GIT_URL: '${{ secrets.PANTHEON_GIT_URL }}'
        PANTHEON_SITE_ID: '${{ secrets.SITE_UUID }}'
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        ssh-keyscan -p 2222 codeserver.dev.${PANTHEON_SITE_ID}.drush.in >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/private.key
        eval `ssh-agent -s`
        ssh-add ~/.ssh/private.key
        git remote add pantheon $PANTHEON_GIT_URL
        git push pantheon HEAD:master