name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: theme_dir

    - name: Build and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PANTHEON_SITE_ID: ${{ secrets.SITE_UUID }}
        PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}
        THEME_NAME: ${{ github.event.repository.name }}
      run: |
        cd ${{ github.workspace }}
        mkdir ~/.ssh
        ssh-keyscan -p 2222 codeserver.dev.${PANTHEON_SITE_ID}.drush.in >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        eval `ssh-agent -s`
        ssh-add ~/.ssh/private.key
        git clone ${PANTHEON_GIT_URL} wordpress
        ls -lah
        rm -rf wordpress/wp-content/themes/${THEME_NAME}/*
        mv /home/runner/work/wp-actions-demo/theme_dir/* wordpress/wp-content/themes
        rm -rf wordpress/wp-content/themes/${THEME_NAME}/.git
        git add .
        git commit . --message="Deploy from GitHub: ${{ github.ref }}"
        git push origin HEAD:master